# Generated by Django 2.2.3 on 2019-07-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=30)),
                ('channel', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('os', models.CharField(max_length=20)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('installs', models.IntegerField()),
                ('spend', models.FloatField()),
                ('revenue', models.FloatField()),
            ],
            options={
                'db_table': 'metrics',
            },
        ),
    ]
